# Generated by Django 4.0.5 on 2022-07-11 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrecipient',
            name='date_of_birthsday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='age_disabled',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('18-35 лет', '18-35 лет'), ('35-60 лет', '35-60 лет'), ('старше 60 лет', 'старше 60 лет')], default='НЕТ', max_length=13),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='age_pensioner',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('до 54 лет', 'до 54 лет'), ('55-74 лет', '55-74 лет'), ('старше 75 лет', 'старше 75 лет')], default='НЕТ', max_length=13),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='comment',
            field=models.TextField(blank=True, null=''),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='date_of_appeal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='disabled',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('ИНВ 1гр', 'ИНВ 1гр'), ('ИНВ 2гр', 'ИНВ 2гр'), ('ИНВ 3гр', 'ИНВ 3гр')], default='НЕТ', max_length=7),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='employment',
            field=models.CharField(choices=[('Работает', 'Работает'), ('Не работает', 'Не работает')], default='Работает', max_length=11),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='fio',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='fluorography',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='mls',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('МЛС', 'МЛС')], default='НЕТ', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='mls_begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='mls_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='narkology',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('На учете', 'На учете'), ('В диспансере', 'В диспансере')], default='НЕТ', max_length=12),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='number_room',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='pensioner',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('Пенс', 'Пенс')], default='НЕТ', max_length=4),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='period_time_begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='period_time_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='pnd',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('На учете', 'На учете'), ('В диспансере', 'В диспансере')], default='НЕТ', max_length=12),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='reason_end',
            field=models.CharField(choices=[('НЕТ', 'НЕТ'), ('Продлен договор', 'Продлен договор'), ('Смерть', 'Смерть'), ('Решение жилищного вопроса', 'Решение жилищного вопроса'), ('Нарушение режима', 'Нарушение режима'), ('Оформление в др. соц. учреждения', 'Оформление в др. соц. учреждения'), ('Прочее', 'Прочее')], default='НЕТ', max_length=33),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='residence',
            field=models.CharField(choices=[('Ж', 'Ж'), ('П', 'П')], default='Ж', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='social_status',
            field=models.CharField(choices=[('БОМЖ', 'БОМЖ'), ('Не бездомный', 'Не бездомный')], default='БОМЖ', max_length=14),
        ),
        migrations.AlterField(
            model_name='cardrecipient',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
